// <auto-generated />
using System;
using InkVerse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InkVerse.Api.Migrations
{
    [DbContext(typeof(InkVerseDB))]
    partial class InkVerseDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFanfic")
                        .HasColumnType("bit");

                    b.Property<int>("OriginType")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReadCount")
                        .HasColumnType("int");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalViews")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerseType")
                        .HasColumnType("int");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.Property<int>("BooksID")
                        .HasColumnType("int");

                    b.Property<int>("GenresID")
                        .HasColumnType("int");

                    b.HasKey("BooksID", "GenresID");

                    b.HasIndex("GenresID");

                    b.ToTable("BookGenre", (string)null);
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.Property<int>("BooksID")
                        .HasColumnType("int");

                    b.Property<int>("TagsID")
                        .HasColumnType("int");

                    b.HasKey("BooksID", "TagsID");

                    b.HasIndex("TagsID");

                    b.ToTable("BookTag", (string)null);
                });

            modelBuilder.Entity("Chapter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ArcId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WordCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ArcId");

                    b.HasIndex("BookId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("Chapters");
                });

            modelBuilder.Entity("ChapterComment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ChapterComments");
                });

            modelBuilder.Entity("ChapterCommentReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CommentId", "UserId")
                        .IsUnique();

                    b.ToTable("ChapterCommentReaction");
                });

            modelBuilder.Entity("Genre", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Name = "Fantasy"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Name = "Romance"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            Name = "Urban"
                        },
                        new
                        {
                            ID = 5,
                            IsActive = true,
                            Name = "Mystery"
                        },
                        new
                        {
                            ID = 6,
                            IsActive = true,
                            Name = "Horror"
                        },
                        new
                        {
                            ID = 7,
                            IsActive = true,
                            Name = "Historical"
                        },
                        new
                        {
                            ID = 8,
                            IsActive = true,
                            Name = "Adventure"
                        },
                        new
                        {
                            ID = 9,
                            IsActive = true,
                            Name = "Realistic"
                        },
                        new
                        {
                            ID = 10,
                            IsActive = true,
                            Name = "Non-Fiction"
                        },
                        new
                        {
                            ID = 11,
                            IsActive = true,
                            Name = "Fanfiction"
                        });
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Arc", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.ToTable("Arcs");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.BookTrend", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TrendID")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookId", "TrendID");

                    b.HasIndex("TrendID");

                    b.ToTable("BookTrends");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReadingProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ChapterId");

                    b.HasIndex("BookId", "UserId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("ReadingProgress");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReviewReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewReplies");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReviewReplyReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewReplyId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewReplyId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewReplyReactions");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.TrendEnti.Trend", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<double>("CanonIntegration")
                        .HasColumnType("float");

                    b.Property<double>("CharacterAccuracy")
                        .HasColumnType("float");

                    b.Property<double>("ChemistryRelationships")
                        .HasColumnType("float");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("EmotionalDamage")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("PlotCreativity")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("ReviewTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("ReviewReaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewReaction");
                });

            modelBuilder.Entity("Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Name = "Comedy"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Name = "Drama"
                        },
                        new
                        {
                            ID = 4,
                            IsActive = true,
                            Name = "Thriller"
                        },
                        new
                        {
                            ID = 5,
                            IsActive = true,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            ID = 6,
                            IsActive = true,
                            Name = "Martial Arts"
                        },
                        new
                        {
                            ID = 7,
                            IsActive = true,
                            Name = "Cultivation"
                        },
                        new
                        {
                            ID = 8,
                            IsActive = true,
                            Name = "Eastern Fantasy"
                        },
                        new
                        {
                            ID = 9,
                            IsActive = true,
                            Name = "Western Fantasy"
                        },
                        new
                        {
                            ID = 10,
                            IsActive = true,
                            Name = "Game Elements"
                        },
                        new
                        {
                            ID = 11,
                            IsActive = true,
                            Name = "System"
                        },
                        new
                        {
                            ID = 12,
                            IsActive = true,
                            Name = "LitRPG"
                        },
                        new
                        {
                            ID = 13,
                            IsActive = true,
                            Name = "Isekai"
                        },
                        new
                        {
                            ID = 14,
                            IsActive = true,
                            Name = "Reincarnation"
                        },
                        new
                        {
                            ID = 15,
                            IsActive = true,
                            Name = "Transmigration"
                        },
                        new
                        {
                            ID = 16,
                            IsActive = true,
                            Name = "Time Travel"
                        },
                        new
                        {
                            ID = 17,
                            IsActive = true,
                            Name = "Modern Day"
                        },
                        new
                        {
                            ID = 18,
                            IsActive = true,
                            Name = "Wuxia"
                        },
                        new
                        {
                            ID = 19,
                            IsActive = true,
                            Name = "Xianxia"
                        },
                        new
                        {
                            ID = 20,
                            IsActive = true,
                            Name = "Xuanhuan"
                        },
                        new
                        {
                            ID = 21,
                            IsActive = true,
                            Name = "Superpowers"
                        },
                        new
                        {
                            ID = 22,
                            IsActive = true,
                            Name = "Magic"
                        },
                        new
                        {
                            ID = 23,
                            IsActive = true,
                            Name = "Alchemy"
                        },
                        new
                        {
                            ID = 24,
                            IsActive = true,
                            Name = "Beasts"
                        },
                        new
                        {
                            ID = 25,
                            IsActive = true,
                            Name = "Dungeons"
                        },
                        new
                        {
                            ID = 26,
                            IsActive = true,
                            Name = "Kingdom Building"
                        },
                        new
                        {
                            ID = 27,
                            IsActive = true,
                            Name = "Harem"
                        },
                        new
                        {
                            ID = 28,
                            IsActive = true,
                            Name = "Reverse Harem"
                        },
                        new
                        {
                            ID = 29,
                            IsActive = true,
                            Name = "Yaoi (BL)"
                        },
                        new
                        {
                            ID = 30,
                            IsActive = true,
                            Name = "Yuri (GL)"
                        },
                        new
                        {
                            ID = 31,
                            IsActive = true,
                            Name = "Smut"
                        },
                        new
                        {
                            ID = 32,
                            IsActive = true,
                            Name = "Adult"
                        },
                        new
                        {
                            ID = 33,
                            IsActive = true,
                            Name = "R-18"
                        },
                        new
                        {
                            ID = 34,
                            IsActive = true,
                            Name = "Psychological"
                        },
                        new
                        {
                            ID = 35,
                            IsActive = true,
                            Name = "Tragedy"
                        },
                        new
                        {
                            ID = 36,
                            IsActive = true,
                            Name = "Antihero"
                        },
                        new
                        {
                            ID = 37,
                            IsActive = true,
                            Name = "Overpowered"
                        },
                        new
                        {
                            ID = 38,
                            IsActive = true,
                            Name = "Weak to Strong"
                        },
                        new
                        {
                            ID = 39,
                            IsActive = true,
                            Name = "Villain MC"
                        },
                        new
                        {
                            ID = 40,
                            IsActive = true,
                            Name = "Female Lead"
                        },
                        new
                        {
                            ID = 41,
                            IsActive = true,
                            Name = "Male Lead"
                        },
                        new
                        {
                            ID = 42,
                            IsActive = true,
                            Name = "Child Protagonist"
                        },
                        new
                        {
                            ID = 43,
                            IsActive = true,
                            Name = "Non-Human Protagonist"
                        },
                        new
                        {
                            ID = 44,
                            IsActive = true,
                            Name = "Monster MC"
                        },
                        new
                        {
                            ID = 45,
                            IsActive = true,
                            Name = "Vampires"
                        },
                        new
                        {
                            ID = 46,
                            IsActive = true,
                            Name = "Werewolves"
                        },
                        new
                        {
                            ID = 47,
                            IsActive = true,
                            Name = "Demons"
                        },
                        new
                        {
                            ID = 48,
                            IsActive = true,
                            Name = "Angels"
                        },
                        new
                        {
                            ID = 49,
                            IsActive = true,
                            Name = "Gods"
                        },
                        new
                        {
                            ID = 50,
                            IsActive = true,
                            Name = "Revenge"
                        },
                        new
                        {
                            ID = 51,
                            IsActive = true,
                            Name = "Romantic Subplot"
                        },
                        new
                        {
                            ID = 52,
                            IsActive = true,
                            Name = "Slow Burn"
                        },
                        new
                        {
                            ID = 53,
                            IsActive = true,
                            Name = "Fast Paced"
                        },
                        new
                        {
                            ID = 54,
                            IsActive = true,
                            Name = "Cold MC"
                        },
                        new
                        {
                            ID = 55,
                            IsActive = true,
                            Name = "Shameless MC"
                        },
                        new
                        {
                            ID = 56,
                            IsActive = true,
                            Name = "Smart MC"
                        },
                        new
                        {
                            ID = 57,
                            IsActive = true,
                            Name = "Evil MC"
                        },
                        new
                        {
                            ID = 58,
                            IsActive = true,
                            Name = "Kind MC"
                        },
                        new
                        {
                            ID = 59,
                            IsActive = true,
                            Name = "Guilds"
                        },
                        new
                        {
                            ID = 60,
                            IsActive = true,
                            Name = "Empires"
                        },
                        new
                        {
                            ID = 61,
                            IsActive = true,
                            Name = "School Life"
                        },
                        new
                        {
                            ID = 62,
                            IsActive = true,
                            Name = "Magic Academy"
                        },
                        new
                        {
                            ID = 63,
                            IsActive = true,
                            Name = "Clans"
                        },
                        new
                        {
                            ID = 64,
                            IsActive = true,
                            Name = "Sect"
                        },
                        new
                        {
                            ID = 65,
                            IsActive = true,
                            Name = "Apocalypse"
                        },
                        new
                        {
                            ID = 66,
                            IsActive = true,
                            Name = "Zombie"
                        },
                        new
                        {
                            ID = 67,
                            IsActive = true,
                            Name = "Cyberpunk"
                        },
                        new
                        {
                            ID = 68,
                            IsActive = true,
                            Name = "Steampunk"
                        },
                        new
                        {
                            ID = 69,
                            IsActive = true,
                            Name = "Futuristic"
                        },
                        new
                        {
                            ID = 70,
                            IsActive = true,
                            Name = "Virtual Reality"
                        },
                        new
                        {
                            ID = 71,
                            IsActive = true,
                            Name = "AI"
                        },
                        new
                        {
                            ID = 72,
                            IsActive = true,
                            Name = "Multiverse"
                        },
                        new
                        {
                            ID = 73,
                            IsActive = true,
                            Name = "Parallel Worlds"
                        },
                        new
                        {
                            ID = 74,
                            IsActive = true,
                            Name = "Tower Climbing"
                        },
                        new
                        {
                            ID = 75,
                            IsActive = true,
                            Name = "Trials"
                        },
                        new
                        {
                            ID = 76,
                            IsActive = true,
                            Name = "Quests"
                        },
                        new
                        {
                            ID = 77,
                            IsActive = true,
                            Name = "Crafting"
                        },
                        new
                        {
                            ID = 78,
                            IsActive = true,
                            Name = "Politics"
                        },
                        new
                        {
                            ID = 79,
                            IsActive = true,
                            Name = "Espionage"
                        },
                        new
                        {
                            ID = 80,
                            IsActive = true,
                            Name = "Military"
                        },
                        new
                        {
                            ID = 81,
                            IsActive = true,
                            Name = "Survival"
                        },
                        new
                        {
                            ID = 82,
                            IsActive = true,
                            Name = "Dark"
                        },
                        new
                        {
                            ID = 83,
                            IsActive = true,
                            Name = "Lighthearted"
                        },
                        new
                        {
                            ID = 84,
                            IsActive = true,
                            Name = "Parody"
                        },
                        new
                        {
                            ID = 85,
                            IsActive = true,
                            Name = "Original Story"
                        });
                });

            modelBuilder.Entity("UserLibrary", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInLibrary")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastReadChapterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("BookId");

                    b.HasIndex("LastReadChapterId");

                    b.HasIndex("UserId", "BookId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("UserLibraries");
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookGenre", b =>
                {
                    b.HasOne("Book", null)
                        .WithMany()
                        .HasForeignKey("BooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookTag", b =>
                {
                    b.HasOne("Book", null)
                        .WithMany()
                        .HasForeignKey("BooksID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chapter", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Arc", "Arc")
                        .WithMany("Chapters")
                        .HasForeignKey("ArcId");

                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arc");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ChapterComment", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", null)
                        .WithMany("Comments")
                        .HasForeignKey("AppUserId");

                    b.HasOne("Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChapterComment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("ParentComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChapterCommentReaction", b =>
                {
                    b.HasOne("ChapterComment", "Comment")
                        .WithMany("Reactions")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Arc", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.BookTrend", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany("BookTrends")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.TrendEnti.Trend", "Trend")
                        .WithMany("BookTrends")
                        .HasForeignKey("TrendID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Trend");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "ApplicationUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReadingProgress", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Chapter", "Chapter")
                        .WithMany()
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReviewReply", b =>
                {
                    b.HasOne("Review", "Review")
                        .WithMany("Replies")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReviewReplyReaction", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.ReviewReply", "ReviewReply")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewReplyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReviewReply");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ReviewReaction", b =>
                {
                    b.HasOne("Review", "Review")
                        .WithMany("Reactions")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserLibrary", b =>
                {
                    b.HasOne("Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Chapter", "LastReadChapter")
                        .WithMany()
                        .HasForeignKey("LastReadChapterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("InkVerse.Api.Entities.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Book");

                    b.Navigation("LastReadChapter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Book", b =>
                {
                    b.Navigation("BookTrends");
                });

            modelBuilder.Entity("ChapterComment", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Arc", b =>
                {
                    b.Navigation("Chapters");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.Identity.AppUser", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Comments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.ReviewReply", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("InkVerse.Api.Entities.TrendEnti.Trend", b =>
                {
                    b.Navigation("BookTrends");
                });

            modelBuilder.Entity("Review", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });
#pragma warning restore 612, 618
        }
    }
}
